### ISSUE TITLE
Recheck with design

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/DSGN-ASSOCIATES-STUDIO-DESIGN#1]
![image](https://user-images.githubusercontent.com/8848858/47779659-50331c00-dd02-11e8-8326-cc8ca909084f.png)

**Comment by Ultimo2905** [comment]
rudnitskih [12:43 PM]
https://github.com/Ultimo2905/DZ-22.10.2018/issues

Давай на лекции обсудим почему не получилось гамбургер сделать

You said that you would say that's wrong
