### ISSUE TITLE
Ссылки

### ISSUE THREAD

**Issue by itsergeysobolit** [Ultimo2905/DSGN-ASSOCIATES-STUDIO-DESIGN#10]
Добавь для ссылок путь. У тебя пустые href="".

**Comment by Ultimo2905** [comment]
Тут немає шлуху.. Якщо поставити # то при натисканні макет відкидує на верх.

**Comment by itsergeysobolit** [comment]
Тому постав javascript:void(0), а там де соц мережі, то посилання на неї

**Comment by Ultimo2905** [comment]
Ти маєш на увазі так? <li><a href="javascript:void(0)" class="first-link-arrow">All</a></li> ???

**Comment by Ultimo2905** [comment]
a href="javascript:void(0)" /a

**Comment by Ultimo2905** [comment]
Ok,  виправив
