### ISSUE TITLE
Interactive elements should response on hover

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/DSGN-ASSOCIATES-STUDIO-DESIGN#12]
![image](https://user-images.githubusercontent.com/8848858/48125613-c649fc80-e287-11e8-8648-4ef6c1404ca2.png)

**Comment by Ultimo2905** [comment]
Interactive elements on hover
opacity: 0.7;
done #12

**Comment by Ultimo2905** [comment]
Зробив #
