### ISSUE TITLE
White line in the right on desktop

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/DSGN-ASSOCIATES-STUDIO-DESIGN#13]
![image](https://user-images.githubusercontent.com/8848858/48125676-ebd70600-e287-11e8-9b17-ac35b8fdaa5d.png)

**Comment by Ultimo2905** [comment]
Я не можу знати де ця волоса. Або вона зникла, або хз... Можете подивитися,та якщо вона є то написати при якому розмірі екрану?

**Comment by rudnitskih** [comment]
Some bug with chrome I think
