### ISSUE TITLE
Wrong links implemenation

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/DSGN-ASSOCIATES-STUDIO-DESIGN#3]
Empty href is bad. Links should have interactive behavior on hover:
![image](https://user-images.githubusercontent.com/8848858/47781553-9e4a1e80-dd06-11e8-8ac9-5213c17deef9.png)

**Comment by Ultimo2905** [comment]
changed
						<a href=""><img src="img/facebook icon.png" alt="facebook"></a>
						<a href=""><img src="img/twitter icon.png" alt="twitter"></a>
						<a href=""><img src="img/linkedin icon.png" alt="linkedin"></a>
						<a href=""><img src="img/g.png" alt="googl"></a>
