### ISSUE TITLE
Don't forget 2x images or SVG

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/DSGN-ASSOCIATES-STUDIO-DESIGN#6]
<img width="228" alt="screen shot 2018-10-31 at 12 20 28" src="https://user-images.githubusercontent.com/8848858/47781844-62638900-dd07-11e8-9d30-40246a9f9fc1.png">

**Comment by Ultimo2905** [comment]
okay, but it's time for it. This is not a problem

**Comment by rudnitskih** [comment]
Why do you think this is not a problem?
