### ISSUE TITLE
Добавить линию

### ISSUE THREAD

**Issue by itsergeysobolit** [Ultimo2905/DSGN-ASSOCIATES-STUDIO-DESIGN#8]
В блоке с id="studio" добавь диагональную линию.
 
Этой линии также нету в остальных блоках.

**Comment by Ultimo2905** [comment]
Вона там стоїть

**Comment by Ultimo2905** [comment]
![image](https://user-images.githubusercontent.com/43437388/47996935-e4d2bb00-e102-11e8-9275-f718ba838dfc.png)

**Comment by itsergeysobolit** [comment]
Це ти локально відкрив чи через посилання що стоїть в описі проекту? Бо я відкрив через посилання і в мене вона не відображається
